// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4n0jmHqc6YwNYHhqANkzcRoIg2soGauI',
    appId: '1:205642343302:web:4226c5b301e8ab116a8207',
    messagingSenderId: '205642343302',
    projectId: 'islami-app-fue',
    authDomain: 'islami-app-fue.firebaseapp.com',
    storageBucket: 'islami-app-fue.firebasestorage.app',
    measurementId: 'G-VEQNHPHKRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBfMoEKUtX8GcCyC_jlB2nnqlotJQEHNo',
    appId: '1:205642343302:android:13349990587980536a8207',
    messagingSenderId: '205642343302',
    projectId: 'islami-app-fue',
    storageBucket: 'islami-app-fue.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4DERLWR3kxgi_yRK53eI0EcXtJdd52AE',
    appId: '1:205642343302:ios:0a3e66abc15787076a8207',
    messagingSenderId: '205642343302',
    projectId: 'islami-app-fue',
    storageBucket: 'islami-app-fue.firebasestorage.app',
    iosBundleId: 'edu.fue.islamiAppFue',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4DERLWR3kxgi_yRK53eI0EcXtJdd52AE',
    appId: '1:205642343302:ios:0a3e66abc15787076a8207',
    messagingSenderId: '205642343302',
    projectId: 'islami-app-fue',
    storageBucket: 'islami-app-fue.firebasestorage.app',
    iosBundleId: 'edu.fue.islamiAppFue',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4n0jmHqc6YwNYHhqANkzcRoIg2soGauI',
    appId: '1:205642343302:web:ac74919d1423e8526a8207',
    messagingSenderId: '205642343302',
    projectId: 'islami-app-fue',
    authDomain: 'islami-app-fue.firebaseapp.com',
    storageBucket: 'islami-app-fue.firebasestorage.app',
    measurementId: 'G-YG8WF85CXZ',
  );
}
